### ISSUE TITLE
Undocumented tag @modifies does not render correctly.

### ISSUE THREAD

**Issue by albadedan** [amekusa/docolatte#4]
Hi,
Excellent theme, thank you.

I'm not sure if this is a you issue or a jsdoc issue, but got to start somewhere.

According to this issue here: https://github.com/jsdoc/jsdoc/issues/1283
JSDoc has an undocumented `@modifies` tag. The linked commit: https://github.com/jsdoc/jsdoc/commit/2f99af8fbbfb7f19d9f962c40884a13ce38696da suggests that you use it just like the `@param` tag.

However when I use it like that it doesn't render out properly.

If I use the style suggested on the linked issue:

```javascript
/**
  * @modifies {unread} The unread count is updated
  */
  async function_name() {...}
```
It renders like this:
![modifies_1](https://github.com/amekusa/docolatte/assets/115635421/64e7d22e-a331-4559-8d0e-8f1efdd71d76)

If I use the standard `@param` style, like this:

```javascript
/**
  * @modifies {Number} unread The unread count is updated
  */
  async function_name() {...}
```
It renders like this:
![modifies_2](https://github.com/amekusa/docolatte/assets/115635421/1baa7125-6043-4aba-9899-02b871c359e8)

If I use this format:
```javascript
/**
  * @modifies The unread count is updated
  */
  async function_name() {...}
```
It renders this:
![modifies_3](https://github.com/amekusa/docolatte/assets/115635421/c099b7ae-d5f1-4252-956b-32fa7155036a)

Running
`jsdoc -X ....` produces this output (on this style: `@modifies {Number} unread The unread count is updated`):
```javascript
"params": [
            {
                "type": {
                    "names": [
                        "String"
                    ]
                },
                "description": "<p>The id of the notification to mark as read</p>",
                "name": "id"
            }
        ],
"modifies": [
            {
                "type": {
                    "names": [
                        "Number"
                    ]
                },
                "description": "<p>unread The unread count is updated</p>"
            }
        ],
"returns": [
            {
                "type": {
                    "names": [
                        "Boolean"
                    ]
                },
                "description": "<p>true if the database was updated successfully</p>"
            }
        ],
``` 

From this I gather that the reason the name 'unread' doesn't appear is because either the jsdoc parser itself (or the markdown plugin) isn't creating a 'name' key. But there is a description, so why does that not end up in the rendered output?

**Comment by amekusa** [comment]
Hi :) Thank you for reporting the issue.
I tested the following code with the JSDoc's default theme to see if `@modifies` tag is rendered correctly.

```js
/**
 * Test Class
 */
class TestClass {
	/**
	 * Test Function
	 * @modifies {unread} The unread count is updated
	 */
	async function_name() {}
}
```

Because the base logic in Docolatte's HTML generation (data parsing, templating, etc.) is mostly derived from the JSDoc's default theme, if there is a bug in the default theme, Docolatte might also have the same issue.

And this is the result (default theme):
![Screen Shot 2024-03-29 at 12 43 47 PM](https://github.com/amekusa/docolatte/assets/3948302/0c497f85-c3d5-4b60-a02d-00569a405393)

So, I see the same issue in the default theme (missing description).

I guess, maybe this is a templating problem. Let me see if I can fix this.

**Comment by amekusa** [comment]
So, I fixed the template so it can show description of `@modifies` tag.
This is the rendering result:
![Screen Shot 2024-03-29 at 2 15 26 PM](https://github.com/amekusa/docolatte/assets/3948302/725189b4-6373-47fb-bb3d-fb052c85960f)

This is the code:
```js
/**
 * Test Class
 */
class TestClass {

	/**
	 * Test Function with type and description
	 * @modifies {unread} The unread count is updated
	 */
	async function_name1() {}

	/**
	 * Test Function with type only
	 * @modifies {Number}
	 */
	async function_name2() {}

	/**
	 * Test Function with description only
	 * @modifies The unread count is updated
	 */
	async function_name3() {}

	/**
	 * Test Function with multiple types
	 * @modifies {unread|Number} The unread count is updated
	 */
	async function_name4() {}
}
```

You can test the fix I just pushed on `dev` branch. Maybe just copy & paste from the commit log above is faster.

**Comment by amekusa** [comment]
@albadedan If you are good with the fix, I merge it into `master` and publish it to npm.

**Comment by albadedan** [comment]
All looks good to me!

Thanks for the quick fix, really appreciate it.


________________________________
From: amekusa ***@***.***>
Sent: Friday, March 29, 2024 10:31:25 PM
To: amekusa/docolatte ***@***.***>
Cc: Dan Barker ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [amekusa/docolatte] Undocumented tag @modifies does not render correctly. (Issue #4)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@albadedan<https://github.com/albadedan> If you are good with the fix, I merge it into master and publish it to npm.

**Comment by amekusa** [comment]
Just published v4.5.1 with the fix.
I'm also working on more improvements like foldable menu items.
Thank you for your positive feedback, which motivates me a lot!

**Comment by albadedan** [comment]
Just tried this and it all works perfectly, thank you.

Foldable menu items does sound good, I do have a few very large tables and things.
Would be good if there was a global setting to default foldable items to open or closed, but then also override at the comment level for a specific item. Not critical by any means, but would be nice.

Also, unrelated, docolatte is the only theme I've found that worked perfectly with [jsdoc-vuejs](https://github.com/Kocal/jsdoc-vuejs) out of the box. All the other themes I tried seemed to require tedious setup, or had dependency issues.

**Comment by amekusa** [comment]
hmm, I've never tried `jsdoc-vuejs` but, maybe the reason docolatte works well with it is, I try not to change the code derived from JSDoc's default theme as much as I can, so it works exact same as the default theme at a basic level.

About foldable menu items that I'm trying to implement, yes, it should be able to specify the default (or completely turn off) with option.
Not sure if it would/should be able to override at the comment level, since it is purely presentational feature.
But maybe, would be nice if we also can specify which items are/aren't folded with option.

But anyway, I appreciate your feed back!
